### ISSUE TITLE
Benchmark镜像问题

### ISSUE THREAD

**Issue by dds-sysu** [alibaba/eCommerceSearchBench#1]
请问镜像没有放在开源仓库吗？ 自己 build 好慢啊

**Comment by CarpenterLee** [comment]
`query-planner.jar` 是工程编译出来的， 按步骤编译工程会生成该文件。
考虑到工程代码会有变动，故没有将jar包发布到镜像里。

`query-planner.jar` will be generated after building the project.
Considering that the project code may change, we do not release the docker image containing the jar file. You can build it as needed.
