### ISSUE TITLE
workload generator 只能生成一个小时的数据？

### ISSUE THREAD

**Issue by yuxiaoba** [alibaba/eCommerceSearchBench#4]
现在的 workload generator 只能生成一个小时的请求数据，然后在Jmeter中设置访问，似乎没有用到intersesion相关的一个月内的请求数据变化，是不是还缺少有一些代码啊？
如何生成一个月的数据呢？

**Comment by yuxiaoba** [comment]
@CarpenterLee 您有空的时候可以分享一下吗？

**Comment by CarpenterLee** [comment]
数据生成器是Benchmark中重要的一环，我们正在改进，近期会有更新。
请问你们的使用场景是什么，用于科研还是工业评测？

Workload generator is an important module of the Benchmark. We're improving it now, and will release a new version later.
What scenario do you use for? scientific research or industrial evaluation?

**Comment by yuxiaoba** [comment]
我还是中山大学的学生，主要想用您这边的benchmark做一些科研。
